import type { TDiagramTarget } from './types.ts';

type TLocalizedVisualCopy = Readonly<{
  title: string;
  alt: string;
  codeRange?: string;
}>;

const VIETNAMESE_COPY_BY_KEY: Readonly<Record<string, TLocalizedVisualCopy>> = {
  'page-1-system-context': {
    title: 'Bối cảnh hệ thống & bản đồ tác nhân',
    codeRange: 'SRS-BENA-AFF-US-001 — tác nhân và ranh giới tin cậy',
    alt: 'Sơ đồ bối cảnh hệ thống thể hiện Creator, Seller, MCN, Buyer, Operations, các bề mặt Benadep và ranh giới tin cậy bên ngoài.',
  },
  'page-1-end-to-end': {
    title: 'Luồng dữ liệu, tiền & bằng chứng đầu cuối',
    codeRange: 'SP-001–SP-084 — tổng quan',
    alt: 'Luồng đầu cuối từ tài sản affiliate và lượt nhấp qua attribution, hoa hồng theo dòng đơn hàng, sổ cái, đối soát và payout.',
  },
  '2-01-backend': {
    title: 'Vòng đời định danh, onboarding & tài khoản',
    alt: 'Sơ đồ vòng đời backend cho đăng ký affiliate, định danh, xác minh kênh, xét duyệt, kích hoạt, đình chỉ và xác minh lại.',
  },
  '2-02-backend': {
    title: 'Dashboard, ưu đãi, hoa hồng & giới thiệu',
    alt: 'Luồng backend cho khám phá ưu đãi, kiểm tra điều kiện, tham gia, tạo tài sản, giới thiệu và tổng hợp hiệu suất.',
  },
  '2-03-backend': {
    title: 'Link, mã sản phẩm, bộ sưu tập & báo cáo',
    alt: 'Luồng backend cho link theo dõi, mã sản phẩm, xuất bản bộ sưu tập, bằng chứng lượt nhấp, báo cáo chuyển đổi và sao kê thu nhập.',
  },
  '2-04-backend': {
    title: 'Attribution, snapshot tỷ lệ & sổ cái hoa hồng',
    alt: 'Luồng attribution backend từ tập ứng viên và kết quả thắng qua snapshot tỷ lệ bất biến, bút toán dòng đơn hàng và điều chỉnh.',
  },
  '2-05-backend': {
    title: 'Vòng đời thương mại Video ngắn',
    alt: 'Vòng đời backend cho tải Video, gắn sản phẩm, phát hành, khám phá, bằng chứng thương mại, kiểm duyệt và khiếu nại.',
  },
  '2-06-backend': {
    title: 'Vòng đời LIVE Commerce',
    alt: 'Vòng đời backend cho lịch LIVE, kiểm tra trước phiên, ingest, phiên đang hoạt động, ghim sản phẩm, giao dịch người xem, replay và kiểm duyệt.',
  },
  '2-07-backend': {
    title: 'PPS người bán, tỷ lệ & liên hệ Creator',
    alt: 'Vòng đời backend cho người bán tham gia PPS, phiên bản tỷ lệ hoa hồng, khám phá Creator và liên hệ theo phạm vi đồng ý.',
  },
  '2-08-backend': {
    title: 'PPP, cộng tác, hàng mẫu & Seller Affiliate',
    alt: 'Vòng đời backend cho đề xuất, phiên bản hợp đồng, phí đã cấp vốn, vận chuyển hàng mẫu, xét duyệt sản phẩm bàn giao và giải ngân.',
  },
  '2-09-backend': {
    title: 'MCN roster, RBAC & phân chia doanh thu',
    alt: 'Vòng đời backend cho đăng ký MCN, thành viên, vai trò, phân công chiến dịch, chia doanh thu và quyết toán.',
  },
  '2-10-backend': {
    title: 'Đối soát, payout, thuế & khắc phục',
    alt: 'Luồng backend cho xác minh thuế và thanh toán, ví, sao kê, đối soát, tạm giữ, thử lại và điều chỉnh.',
  },
  '2-11-backend': {
    title: 'Gian lận, enforcement & khiếu nại',
    alt: 'Vòng đời backend cho báo cáo gian lận, phân loại vụ việc, đồ thị bằng chứng, quyết định, enforcement, khiếu nại và thu hồi.',
  },
  '2-12-backend': {
    title: 'Phân phối ngoài nền tảng & YouTube Shopping',
    alt: 'Luồng backend cho xác minh tài sản bên ngoài, OAuth, đồng bộ catalog feed, gắn sản phẩm và báo cáo theo kênh.',
  },
  '3-01-ui': {
    title: 'Điều hướng UI định danh & onboarding',
    alt: 'Điều hướng UI giữa trung tâm affiliate, biểu mẫu đăng ký, xác minh kênh, cài đặt và màn hình xét duyệt quản trị.',
  },
  '3-02-ui': {
    title: 'Điều hướng UI dashboard, ưu đãi & giới thiệu',
    alt: 'Điều hướng UI giữa dashboard affiliate, marketplace sản phẩm, chi tiết ưu đãi, lời mời, giới thiệu và quản lý ưu đãi.',
  },
  '3-03-ui': {
    title: 'Điều hướng UI link, bộ sưu tập & báo cáo',
    alt: 'Điều hướng UI giữa trình tạo link, trình tạo mã, quản lý bộ sưu tập, bộ sưu tập công khai và báo cáo tài chính.',
  },
  '3-04-ui': {
    title: 'Điều hướng UI attribution & ledger',
    alt: 'Điều hướng UI giữa chi tiết attribution chuyển đổi, mô phỏng tỷ lệ người bán, ledger Creator và trình khám phá attribution.',
  },
  '3-05-ui': {
    title: 'Điều hướng UI thương mại Video ngắn',
    alt: 'Điều hướng UI ưu tiên mobile giữa feed Video, trình soạn nội dung, bộ chọn sản phẩm, bảng chi tiết, kiểm duyệt và khiếu nại.',
  },
  '3-06-ui': {
    title: 'Điều hướng UI LIVE Commerce',
    alt: 'Điều hướng UI ưu tiên mobile giữa khám phá LIVE, thiết lập, bảng điều khiển Host, phòng Viewer, replay và kiểm duyệt.',
  },
  '3-07-ui': {
    title: 'Điều hướng UI Seller PPS & liên hệ Creator',
    alt: 'Điều hướng UI giữa đăng ký PPS, cấu hình tỷ lệ hoa hồng, danh bạ Creator và đồng ý liên hệ.',
  },
  '3-08-ui': {
    title: 'Điều hướng UI cộng tác PPP',
    alt: 'Điều hướng UI giữa hộp thư cộng tác, trình sửa hợp đồng, theo dõi hàng mẫu, xét duyệt sản phẩm bàn giao và dashboard Seller Affiliate.',
  },
  '3-09-ui': {
    title: 'Điều hướng UI MCN & agency',
    alt: 'Điều hướng UI giữa đăng ký MCN, lời mời roster, RBAC tài khoản phụ, phân công chiến dịch và báo cáo quyết toán.',
  },
  '3-10-ui': {
    title: 'Điều hướng UI payout, thuế & đối soát',
    alt: 'Điều hướng UI giữa ví Creator, thiết lập thuế và thanh toán, sao kê, khắc phục payout và đối soát tài chính.',
  },
  '3-11-ui': {
    title: 'Điều hướng UI gian lận, enforcement & khiếu nại',
    alt: 'Điều hướng UI giữa báo cáo gian lận, hàng đợi rủi ro, đồ thị vụ việc, khiếu nại enforcement và bảng điều khiển thu hồi chính sách.',
  },
  '3-12-ui': {
    title: 'Điều hướng UI phân phối ngoài nền tảng',
    alt: 'Điều hướng UI giữa sổ đăng ký tài sản, kết nối YouTube OAuth, tình trạng feed sản phẩm bên ngoài và báo cáo kênh.',
  },
  'page-4-traceability': {
    title: 'Chuỗi truy vết yêu cầu',
    codeRange: 'SP → CN → QT → MH/non-UI → KT → bằng chứng',
    alt: 'Chuỗi truy vết từ kết quả Shopee quan sát được qua yêu cầu SRS và ca kiểm thử đến bằng chứng cùng cổng xác thực.',
  },
  'page-4-release-gate': {
    title: 'Cổng kiểm thử, bằng chứng & phát hành',
    codeRange: 'KT-001–KT-120 và bằng chứng phát hành',
    alt: 'Cổng phát hành kết hợp bằng chứng capability, golden, thuật toán, bảo mật, khả năng tiếp cận, tài chính và source code.',
  },
};

const legacyVisualCaption = (scope: string): string =>
  `${scope}. Solid=request/navigation; dashed=async; dotted=audit/evidence. Visual aid only; normative text remains authoritative.`;

const vietnameseVisualCaption = (scope: string): string =>
  `${scope}. Đường liền biểu thị yêu cầu hoặc điều hướng; đường đứt biểu thị xử lý bất đồng bộ; đường chấm biểu thị audit hoặc bằng chứng. Hình minh họa; nội dung SRS chuẩn tắc vẫn là nguồn quyết định.`;

const target = (
  value: Omit<
    TDiagramTarget,
    'nextVersion' | 'currentVersion' | 'caption' | 'legacy'
  >,
): TDiagramTarget => {
  const localized = VIETNAMESE_COPY_BY_KEY[value.key];
  if (!localized) {
    throw new Error(`Missing Vietnamese visual copy for ${value.key}`);
  }
  const codeRange = localized.codeRange ?? value.codeRange;

  return {
    ...value,
    title: localized.title,
    codeRange,
    alt: localized.alt,
    nextVersion: '0.5',
    currentVersion: '0.5',
    caption: vietnameseVisualCaption(codeRange),
    legacy: {
      title: value.title,
      alt: value.alt,
      caption: legacyVisualCaption(value.codeRange),
    },
  };
};

export const DIAGRAM_TARGETS = [
  target({
    key: 'page-1-system-context',
    filename: 'srs-page-1-system-context.svg',
    kind: 'overview',
    pageId: '9dcad27c837882d9963701525cd9e39a',
    pageLabel: 'Page 1',
    title: 'System context & actor map',
    codeRange: 'SRS-BENA-AFF-US-001 actors and trust boundaries',
    previousVersion: '0.2',
    insertBefore: '## Trong phạm vi',
    alt: 'System context showing Creator, Seller, MCN, Buyer, Operations, Benadep surfaces and external trust boundaries.',
  }),
  target({
    key: 'page-1-end-to-end',
    filename: 'srs-page-1-end-to-end-flow.svg',
    kind: 'overview',
    pageId: '9dcad27c837882d9963701525cd9e39a',
    pageLabel: 'Page 1',
    title: 'End-to-end data, money & evidence flow',
    codeRange: 'SP-001–SP-084 overview',
    previousVersion: '0.2',
    insertBefore: '## Luồng sử dụng tổng quát',
    alt: 'End-to-end flow from affiliate asset and click through attribution, order-line commission, ledger, reconciliation and payout.',
  }),
  target({
    key: '2-01-backend',
    filename: 'srs-2-01-backend-lifecycle.svg',
    kind: 'backend',
    pageId: 'a0fad27c837882bd8a5781a0ce5ef4a6',
    pageLabel: '2.01',
    title: 'Identity, onboarding & account lifecycle',
    codeRange: 'CN-001–CN-009',
    previousVersion: '0.2',
    insertBefore: '## Luồng end-to-end',
    alt: 'Backend lifecycle for affiliate application, identity, channel verification, review, activation, suspension and reverification.',
    relatedPageUrl: 'https://app.notion.com/p/502ad27c8378822baeff81acdf027872',
  }),
  target({
    key: '2-02-backend',
    filename: 'srs-2-02-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c83788175ad48e3637264a0c6',
    pageLabel: '2.02',
    title: 'Dashboard, offers, commission discovery & referral',
    codeRange: 'CN-010–CN-019',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for offer discovery, eligibility, enrollment, asset creation, referral and performance aggregation.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378818d87b6c9e72728a9d2',
  }),
  target({
    key: '2-03-backend',
    filename: 'srs-2-03-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c8378815a9ebee9c2cfca01c7',
    pageLabel: '2.03',
    title: 'Link, product code, collection & reporting',
    codeRange: 'CN-020–CN-027',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend flow for tracked link, product code, collection publication, click evidence, conversion report and earning statement.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378817fada9f89511ba99e1',
  }),
  target({
    key: '2-04-backend',
    filename: 'srs-2-04-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881859fcad6114eed59a0',
    pageLabel: '2.04',
    title: 'Attribution, rate snapshot & commission ledger',
    codeRange: 'CN-028–CN-039',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend attribution flow from candidates and winner through immutable rate snapshot, order-line journal and adjustment.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881699337d970fd99a9c4',
  }),
  target({
    key: '2-05-backend',
    filename: 'srs-2-05-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881c1b06ddf6cee307cb4',
    pageLabel: '2.05',
    title: 'Short Video Commerce lifecycle',
    codeRange: 'CN-040–CN-047',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for video upload, product tagging, publish, discovery, commerce evidence, moderation and appeal.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788162bc0bebeb19eb3654',
  }),
  target({
    key: '2-06-backend',
    filename: 'srs-2-06-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881e09720ee71d2a4239a',
    pageLabel: '2.06',
    title: 'LIVE Commerce lifecycle',
    codeRange: 'CN-048–CN-052',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for LIVE schedule, preflight, ingest, active session, product pin, viewer commerce, replay and moderation.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788147a823e5f65aae74c8',
  }),
  target({
    key: '2-07-backend',
    filename: 'srs-2-07-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881568f2ed253143d14b1',
    pageLabel: '2.07',
    title: 'Seller PPS, rates & creator contact',
    codeRange: 'CN-053–CN-056',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for seller PPS enrollment, commission rate versions, creator discovery and consent-scoped contact.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788149a696d53cfc062b11',
  }),
  target({
    key: '2-08-backend',
    filename: 'srs-2-08-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c8378817b8d1ac107731cc836',
    pageLabel: '2.08',
    title: 'PPP, collaboration, sample & seller affiliate',
    codeRange: 'CN-057–CN-065',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for proposal, contract version, funded fee, sample shipment, deliverable review and release.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378819e8100d2b502000d4e',
  }),
  target({
    key: '2-09-backend',
    filename: 'srs-2-09-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c83788133902fe4ce1910435e',
    pageLabel: '2.09',
    title: 'MCN roster, RBAC & revenue split',
    codeRange: 'CN-066–CN-072',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for MCN application, membership, roles, campaign assignment, revenue split and settlement.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881549d4af92e27878a6c',
  }),
  target({
    key: '2-10-backend',
    filename: 'srs-2-10-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c8378814d9d0fe3849c42f3fc',
    pageLabel: '2.10',
    title: 'Reconciliation, payout, tax & remediation',
    codeRange: 'CN-073–CN-077',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend flow for tax and payment verification, wallet, statements, reconciliation, holds, retries and corrections.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788173ae60c1f3ddda9fe0',
  }),
  target({
    key: '2-11-backend',
    filename: 'srs-2-11-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881348366cc8572374d38',
    pageLabel: '2.11',
    title: 'Fraud, enforcement & appeals',
    codeRange: 'CN-078–CN-082',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend lifecycle for fraud report, case triage, evidence graph, decision, enforcement, appeal and recall.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881998be8c368ba4437b9',
  }),
  target({
    key: '2-12-backend',
    filename: 'srs-2-12-backend-lifecycle.svg',
    kind: 'backend',
    pageId: '3a0ad27c837881b4beb5e186e857672b',
    pageLabel: '2.12',
    title: 'External distribution & YouTube Shopping',
    codeRange: 'CN-083–CN-084',
    previousVersion: '0.2',
    insertBefore: '## Luồng xử lý end-to-end',
    alt: 'Backend flow for external property verification, OAuth, catalog feed sync, product tagging and channel reporting.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881b1b359f8df360d1bef',
  }),
  target({
    key: '3-01-ui',
    filename: 'srs-3-01-ui-navigation.svg',
    kind: 'ui',
    pageId: '502ad27c8378822baeff81acdf027872',
    pageLabel: '3.01',
    title: 'Identity and onboarding UI navigation',
    codeRange: 'MH-001–MH-005',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across affiliate center, application, channel verification, settings and admin review screens.',
    relatedPageUrl: 'https://app.notion.com/p/a0fad27c837882bd8a5781a0ce5ef4a6',
  }),
  target({
    key: '3-02-ui',
    filename: 'srs-3-02-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c8378818d87b6c9e72728a9d2',
    pageLabel: '3.02',
    title: 'Dashboard, offer and referral UI navigation',
    codeRange: 'MH-006–MH-011',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across affiliate dashboard, product marketplace, offer detail, invitations, referral and offer management.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788175ad48e3637264a0c6',
  }),
  target({
    key: '3-03-ui',
    filename: 'srs-3-03-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c8378817fada9f89511ba99e1',
    pageLabel: '3.03',
    title: 'Link, collection and reporting UI navigation',
    codeRange: 'MH-012–MH-017',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across link builder, code generator, collection manager, public collection and financial reports.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378815a9ebee9c2cfca01c7',
  }),
  target({
    key: '3-04-ui',
    filename: 'srs-3-04-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c837881699337d970fd99a9c4',
    pageLabel: '3.04',
    title: 'Attribution and ledger UI navigation',
    codeRange: 'MH-018–MH-021',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across conversion attribution detail, seller rate simulator, creator ledger and attribution explorer.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881859fcad6114eed59a0',
  }),
  target({
    key: '3-05-ui',
    filename: 'srs-3-05-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c83788162bc0bebeb19eb3654',
    pageLabel: '3.05',
    title: 'Short Video Commerce UI navigation',
    codeRange: 'MH-022–MH-026',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'Mobile-first UI navigation across video feed, composer, product picker, detail sheet, moderation and appeal.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881c1b06ddf6cee307cb4',
  }),
  target({
    key: '3-06-ui',
    filename: 'srs-3-06-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c83788147a823e5f65aae74c8',
    pageLabel: '3.06',
    title: 'LIVE Commerce UI navigation',
    codeRange: 'MH-027–MH-031',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'Mobile-first UI navigation across LIVE discovery, setup, host console, viewer room, replay and moderation.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881e09720ee71d2a4239a',
  }),
  target({
    key: '3-07-ui',
    filename: 'srs-3-07-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c83788149a696d53cfc062b11',
    pageLabel: '3.07',
    title: 'Seller PPS and creator contact UI navigation',
    codeRange: 'MH-032–MH-035',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across PPS enrollment, commission rate configuration, creator directory and contact consent.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881568f2ed253143d14b1',
  }),
  target({
    key: '3-08-ui',
    filename: 'srs-3-08-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c8378819e8100d2b502000d4e',
    pageLabel: '3.08',
    title: 'PPP collaboration UI navigation',
    codeRange: 'MH-036–MH-040',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across collaboration inbox, contract editor, sample tracker, deliverable review and seller affiliate dashboard.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378817b8d1ac107731cc836',
  }),
  target({
    key: '3-09-ui',
    filename: 'srs-3-09-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c837881549d4af92e27878a6c',
    pageLabel: '3.09',
    title: 'MCN and agency UI navigation',
    codeRange: 'MH-041–MH-045',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across MCN application, roster invitations, sub-account RBAC, campaign assignments and settlement reports.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c83788133902fe4ce1910435e',
  }),
  target({
    key: '3-10-ui',
    filename: 'srs-3-10-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c83788173ae60c1f3ddda9fe0',
    pageLabel: '3.10',
    title: 'Payout, tax and reconciliation UI navigation',
    codeRange: 'MH-046–MH-050',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across creator wallet, tax and payment setup, statements, payout remediation and finance reconciliation.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c8378814d9d0fe3849c42f3fc',
  }),
  target({
    key: '3-11-ui',
    filename: 'srs-3-11-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c837881998be8c368ba4437b9',
    pageLabel: '3.11',
    title: 'Fraud, enforcement and appeal UI navigation',
    codeRange: 'MH-051–MH-055',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across fraud report, risk queue, case graph, enforcement appeal and policy recall console.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881348366cc8572374d38',
  }),
  target({
    key: '3-12-ui',
    filename: 'srs-3-12-ui-navigation.svg',
    kind: 'ui',
    pageId: '3a0ad27c837881b1b359f8df360d1bef',
    pageLabel: '3.12',
    title: 'External distribution UI navigation',
    codeRange: 'MH-056–MH-059',
    previousVersion: '0.4',
    insertBefore: '### Quy ước Component Contract',
    alt: 'UI navigation across property registry, YouTube OAuth connection, external product feed health and channel reports.',
    relatedPageUrl: 'https://app.notion.com/p/3a0ad27c837881b4beb5e186e857672b',
  }),
  target({
    key: 'page-4-traceability',
    filename: 'srs-page-4-traceability.svg',
    kind: 'test',
    pageId: 'cd0ad27c83788331af0301132464b33b',
    pageLabel: 'Page 4',
    title: 'Requirement traceability chain',
    codeRange: 'SP → CN → QT → MH/non-UI → KT → evidence',
    previousVersion: '0.2',
    insertBefore: '## A. Kịch bản theo capability',
    alt: 'Traceability chain from observable Shopee outcome through SRS requirements and test cases to evidence and validation gates.',
  }),
  target({
    key: 'page-4-release-gate',
    filename: 'srs-page-4-release-evidence-gate.svg',
    kind: 'test',
    pageId: 'cd0ad27c83788331af0301132464b33b',
    pageLabel: 'Page 4',
    title: 'Test and evidence release gate',
    codeRange: 'KT-001–KT-120 and release evidence',
    previousVersion: '0.2',
    insertBefore: '## Điều kiện hoàn thành',
    alt: 'Release gate combining capability, golden, algorithm, security, accessibility, finance and source-code evidence.',
  }),
] as const satisfies readonly TDiagramTarget[];

export const TARGET_BY_KEY = new Map(
  DIAGRAM_TARGETS.map((item) => [item.key, item] as const),
);
