import { TARGET_BY_KEY } from './manifest.ts';

import type {
  TBadge,
  TDiagramColumn,
  TDiagramEdge,
  TDiagramNode,
  TDiagramSpec,
  TEdgeStyle,
  TTone,
} from './types.ts';

const node = (
  id: string,
  label: string,
  detail: string,
  tone: TTone,
  badge?: TBadge,
): TDiagramNode =>
  badge ? { id, label, detail, tone, badge } : { id, label, detail, tone };

const edge = (
  from: string,
  to: string,
  label: string,
  style: TEdgeStyle = 'solid',
): TDiagramEdge => ({ from, to, label, style });

const column = (
  title: string,
  nodes: readonly TDiagramNode[],
  allowVisualReorder = false,
): TDiagramColumn =>
  allowVisualReorder
    ? { title, nodes, allowVisualReorder: true }
    : { title, nodes };

const surfaceBoundary = (
  key: string,
  surfaces: readonly TDiagramNode[],
): TDiagramColumn =>
  column('Ranh giới bề mặt', [
    node(
      `${key}-entry`,
      'Điểm vào/xác thực',
      'Điểm vào tuyến đã xác thực, có cổng vai trò và trạng thái tài khoản.',
      'system',
      'Hiện có',
    ),
    ...surfaces,
  ]);

const authoritativeOutcome = (
  key: string,
  result: string,
  states: string,
  remediation: string,
  audit: string,
): TDiagramColumn =>
  column('Kết quả chuẩn tắc', [
    node(
      `${key}-api`,
      'Kết quả chuẩn tắc BFF/API',
      result,
      'system',
      'Mở rộng',
    ),
    node(`${key}-states`, 'Đang tải/lỗi/từ chối', states, 'ops'),
    node(`${key}-remediation`, 'Khắc phục / thoát an toàn', remediation, 'ops'),
    node(`${key}-audit`, 'Audit / tham chiếu', audit, 'system'),
  ]);

const uiSpec = (
  key: string,
  scope: string,
  columns: readonly TDiagramColumn[],
  edges: readonly TDiagramEdge[],
): TDiagramSpec => {
  const target = TARGET_BY_KEY.get(key);
  if (!target) {
    throw new Error(`Unknown UI diagram target: ${key}`);
  }
  const nodePrefix = key.replace(/-ui$/, '');

  return {
    key,
    title: target.title,
    subtitle: target.codeRange,
    scope,
    columns,
    edges: [
      ...edges,
      edge(
        `${nodePrefix}-api`,
        `${nodePrefix}-states`,
        'đang tải / lỗi / từ chối',
      ),
      edge(
        `${nodePrefix}-states`,
        `${nodePrefix}-remediation`,
        'thử lại / tác vụ được phép',
      ),
    ],
  };
};

export const UI_SPECS: readonly TDiagramSpec[] = [
  uiSpec(
    '3-01-ui',
    'Creator onboarding và quản trị xét duyệt; needs_action hoặc bị từ chối sẽ quay về đúng phần biểu mẫu.',
    [
      surfaceBoundary('3-01', [
        node(
          '3-01-storefront',
          'Storefront',
          'Các tuyến tài khoản Creator và trung tâm affiliate.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-01-admin',
          'Medusa Admin',
          'Deep-link quản trị mở hồ sơ đã nộp để xét duyệt.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Hành trình Creator', [
        node(
          'mh-001',
          'MH-001 Điều kiện tham gia',
          'Hiển thị điều kiện, trạng thái tài khoản và hành động tiếp theo được phép.',
          'creator',
          'Mới',
        ),
        node(
          'mh-002',
          'MH-002 Đơn đăng ký',
          'Xác thực các trường định danh, liên hệ, đồng ý và thông tin người tham gia.',
          'creator',
          'Mới',
        ),
        node(
          'mh-003',
          'MH-003 Xác minh kênh',
          'Thử thách quyền sở hữu và trạng thái xác minh chuẩn tắc.',
          'creator',
          'Mới',
        ),
        node(
          'mh-004',
          'MH-004 Cài đặt',
          'Cho phép sửa hồ sơ, kênh, đồng ý và trạng thái tài khoản.',
          'creator',
          'Mới',
        ),
      ]),
      column('Xét duyệt vận hành', [
        node(
          'mh-005',
          'MH-005 Xét duyệt',
          'Bằng chứng quản trị, quyết định, mã lý do và yêu cầu chỉnh sửa.',
          'ops',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-01',
        'Trạng thái đơn đăng ký, xác minh và xét duyệt từ BFF/API.',
        'Đang tải giữ nguyên bản nháp; lỗi cho phép thử lại; từ chối sẽ ẩn bằng chứng được bảo vệ.',
        'needs_action hoặc bị từ chối quay về đúng phần biểu mẫu; trường hợp khác thoát an toàn về trung tâm affiliate.',
        'Phiên bản đơn, quyết định xét duyệt, mã lý do và tham chiếu tương quan.',
      ),
    ],
    [
      edge('3-01-entry', 'mh-001', 'điểm vào/xác thực'),
      edge('3-01-storefront', 'mh-001', 'tuyến Creator'),
      edge('mh-001', 'mh-002', 'đủ điều kiện → đăng ký'),
      edge('mh-002', 'mh-003', 'nộp → xác minh'),
      edge('mh-003', 'mh-004', 'đã xác minh → cài đặt'),
      edge('3-01-admin', 'mh-005', 'deep-link quản trị'),
      edge('mh-002', '3-01-api', 'nộp đơn'),
      edge('mh-003', '3-01-api', 'xác minh'),
      edge('mh-005', '3-01-api', 'quyết định'),
      edge('3-01-remediation', 'mh-002', 'đúng phần biểu mẫu'),
      edge('3-01-api', '3-01-audit', 'bằng chứng theo phiên bản', 'dotted'),
    ],
  ),
  uiSpec(
    '3-02-ui',
    'Khám phá dashboard, tài sản ưu đãi, nhánh lời mời và giới thiệu, cùng quản lý ưu đãi của người bán hoặc quản trị.',
    [
      surfaceBoundary('3-02', [
        node(
          '3-02-storefront',
          'Storefront',
          'Các tuyến dashboard, marketplace, lời mời và giới thiệu của Creator.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-02-vendor',
          'Vendor Portal',
          'Điểm vào cấu hình ưu đãi và hoa hồng của người bán.',
          'seller',
          'Mở rộng',
        ),
        node(
          '3-02-admin',
          'Medusa Admin',
          'Điểm vào giám sát ưu đãi đã được phân quyền.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Khám phá & kích hoạt', [
        node(
          'mh-006',
          'MH-006 Bảng Dashboard',
          'Click, đơn hàng, thu nhập, nhiệm vụ và độ mới dữ liệu chuẩn tắc.',
          'creator',
          'Mới',
        ),
        node(
          'mh-007',
          'MH-007 Chợ Marketplace',
          'Ưu đãi đủ điều kiện kèm bộ lọc, tỷ lệ, điều khoản và khả dụng.',
          'creator',
          'Mới',
        ),
        node(
          'mh-008',
          'MH-008 Chi tiết ưu đãi',
          'Phiên bản hiện tại, điều kiện, đăng ký tham gia và hành động tài sản.',
          'creator',
          'Mới',
        ),
      ]),
      column('Deep-link & quản lý', [
        node(
          'mh-009',
          'MH-009 Lời mời',
          'Deep-link lời mời kèm trạng thái, điều khoản theo phiên bản và phản hồi.',
          'creator',
          'Mới',
        ),
        node(
          'mh-010',
          'MH-010 Giới thiệu',
          'Link giới thiệu, trạng thái lời mời, điều kiện và kết quả thu nhập.',
          'creator',
          'Mới',
        ),
        node(
          'mh-011',
          'MH-011 Quản lý ưu đãi',
          'Phiên bản tỷ lệ, nhắm mục tiêu, tạm dừng và kiểm soát audit cho người bán/quản trị.',
          'seller',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-02',
        'Điều kiện, đăng ký, lời mời, giới thiệu và phiên bản ưu đãi từ BFF/API.',
        'Đang tải dùng skeleton ổn định; lỗi cho phép thử lại; từ chối loại bỏ hành động không đủ điều kiện.',
        'Ưu đãi cũ buộc làm mới phiên bản trước khi thay đổi; thoát an toàn vẫn giữ bộ lọc.',
        'Phiên bản ưu đãi, quyết định điều kiện, thời điểm dữ liệu mới và tham chiếu hành động.',
      ),
    ],
    [
      edge('3-02-entry', 'mh-006', 'điểm vào/xác thực'),
      edge('3-02-storefront', 'mh-006', 'tuyến Creator'),
      edge('mh-006', 'mh-007', 'duyệt ưu đãi'),
      edge('mh-007', 'mh-008', 'chọn ưu đãi'),
      edge('3-02-entry', 'mh-009', 'deep-link lời mời'),
      edge('3-02-entry', 'mh-010', 'luồng giới thiệu'),
      edge('3-02-vendor', 'mh-011', 'người bán quản lý'),
      edge('3-02-admin', 'mh-011', 'quản trị giám sát'),
      edge('mh-008', '3-02-api', 'đăng ký / tạo tài sản'),
      edge('mh-009', '3-02-api', 'chấp nhận / từ chối'),
      edge('mh-010', '3-02-api', 'trạng thái giới thiệu'),
      edge('mh-011', '3-02-api', 'xuất bản phiên bản'),
      edge('3-02-api', '3-02-audit', 'độ mới và phiên bản', 'dotted'),
    ],
  ),
  uiSpec(
    '3-03-ui',
    'Link theo dõi, mã sản phẩm, xuất bản bộ sưu tập, báo cáo chuyển đổi và các màn hình thu nhập hoặc thanh toán.',
    [
      column('Ranh giới bề mặt', [
        node(
          '3-03-auth-entry',
          'Storefront — Creator đã xác thực',
          'Điểm vào/xác thực cho công cụ tài sản Creator và báo cáo riêng tư.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-03-public-entry',
          'Storefront — Buyer công khai',
          'Điểm vào Buyer công khai để phân giải bộ sưu tập hoặc PDP; không yêu cầu tài khoản affiliate.',
          'system',
          'Mở rộng',
        ),
      ]),
      column('Tạo & xuất bản', [
        node(
          'mh-012',
          'MH-012 Trình tạo link',
          'Đích đến, tham số chiến dịch, xác thực và hành động sao chép.',
          'creator',
          'Mới',
        ),
        node(
          'mh-013',
          'MH-013 Trình tạo mã',
          'Mã sản phẩm, ngữ cảnh kênh, thời hạn và hành động sao chép.',
          'creator',
          'Mới',
        ),
        node(
          'mh-014',
          'MH-014 Bộ sưu tập',
          'Bản nháp, thứ tự sản phẩm, khả năng hiển thị, phiên bản và hành động xuất bản.',
          'creator',
          'Mới',
        ),
      ]),
      column('Phân giải & báo cáo', [
        node(
          'mh-015',
          'MH-015 Buyer/PDP công khai',
          'Đích bộ sưu tập hoặc sản phẩm công khai cho Buyer, kèm ngữ cảnh nguồn.',
          'system',
          'Mở rộng',
        ),
        node(
          'mh-016',
          'MH-016 Chuyển đổi',
          'Các dòng chuyển đổi theo order-line, trạng thái attribution và drill-down.',
          'money',
          'Mới',
        ),
        node(
          'mh-017',
          'MH-017 Thu nhập',
          'Màn hình thu nhập, thanh toán, kỳ, trạng thái và xuất dữ liệu.',
          'money',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-03',
        'Đích phân giải, tham chiếu click, dòng chuyển đổi và trạng thái tài chính từ BFF/API.',
        'Đang tải giữ ngữ cảnh truy vấn; lỗi phân giải được nêu rõ; từ chối bảo vệ báo cáo riêng tư.',
        'Lỗi phân giải giữ ngữ cảnh nguồn để thử lại hoặc thoát an toàn về tài sản gốc.',
        'Phiên bản tài sản, nguồn click, tham chiếu order-line, truy vấn báo cáo và tham chiếu xuất dữ liệu.',
      ),
    ],
    [
      edge('3-03-auth-entry', 'mh-012', 'link, mã hoặc bộ sưu tập'),
      edge('3-03-auth-entry', 'mh-013', 'công cụ tạo mã'),
      edge('3-03-auth-entry', 'mh-014', 'công cụ bộ sưu tập'),
      edge('3-03-public-entry', 'mh-015', 'phân giải công khai'),
      edge('mh-012', 'mh-015', 'phân giải link'),
      edge('mh-013', 'mh-015', 'phân giải mã'),
      edge('mh-014', 'mh-015', 'xuất bản bộ sưu tập'),
      edge('3-03-auth-entry', 'mh-016', 'mở báo cáo'),
      edge('mh-016', 'mh-017', 'thu nhập / thanh toán'),
      edge('mh-015', '3-03-api', 'kết quả phân giải'),
      edge('mh-017', '3-03-api', 'truy vấn tài chính'),
      edge('3-03-api', '3-03-audit', 'nguồn / báo cáo', 'dotted'),
    ],
  ),
  uiSpec(
    '3-04-ui',
    'Drill-down báo cáo Creator, mô phỏng tỷ lệ người bán và phát lại attribution cho quản trị đã phân quyền.',
    [
      surfaceBoundary('3-04', [
        node(
          '3-04-storefront',
          'Storefront',
          'Điều hướng dòng báo cáo và ledger của Creator.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-04-vendor',
          'Vendor Portal',
          'Cấu hình người bán mở mô phỏng tỷ lệ và xem trước phiên bản.',
          'seller',
          'Mở rộng',
        ),
        node(
          '3-04-admin',
          'Medusa Admin',
          'Deep-link bằng chứng quản trị cho phép phát lại đã phân quyền.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Chi tiết tài chính', [
        node(
          'mh-018',
          'MH-018 Quyết định Attribution',
          'Chi tiết ứng viên, bên thắng, phiên bản quy tắc và bằng chứng nguồn.',
          'creator',
          'Mới',
        ),
        node(
          'mh-020',
          'MH-020 Sổ cái Ledger',
          'Nhật ký order-line, chuyển trạng thái, điều chỉnh và số dư.',
          'money',
          'Mới',
        ),
      ]),
      column('Công cụ được phân quyền', [
        node(
          'mh-019',
          'MH-019 Mô phỏng tỷ lệ',
          'Đầu vào người bán, phiên bản có hiệu lực, xem trước và kết quả không ràng buộc.',
          'seller',
          'Mới',
        ),
        node(
          'mh-021',
          'MH-021 Trình khám phá',
          'Bằng chứng ứng viên cho quản trị và điều khiển phát lại xác định.',
          'ops',
          'Cổng xác thực thực địa',
        ),
      ]),
      authoritativeOutcome(
        '3-04',
        'Quyết định attribution, phiên bản tỷ lệ, bút toán ledger và bằng chứng phát lại từ BFF/API.',
        'Đang tải giữ định danh dòng; lỗi cho phép thử lại; bị từ chối quyền không lộ bằng chứng được bảo vệ.',
        'Bị từ chối quyền sẽ thoát an toàn về báo cáo được phép, không lộ nội bộ quyết định bí mật.',
        'Phiên bản quyết định, snapshot tỷ lệ, nhật ký ledger, đầu vào phát lại và tham chiếu tương quan.',
      ),
    ],
    [
      edge('3-04-entry', 'mh-018', 'dòng báo cáo'),
      edge('3-04-storefront', 'mh-018', 'tuyến báo cáo Creator'),
      edge('mh-018', 'mh-020', 'chi tiết ledger'),
      edge('3-04-vendor', 'mh-019', 'cấu hình người bán'),
      edge('3-04-admin', 'mh-021', 'bằng chứng quản trị'),
      edge('mh-018', 'mh-021', 'khám phá theo quyền'),
      edge('mh-019', '3-04-api', 'mô phỏng phiên bản'),
      edge('mh-020', '3-04-api', 'truy vấn nhật ký'),
      edge('mh-021', '3-04-api', 'phát lại'),
      edge('3-04-api', '3-04-audit', 'bằng chứng quyết định', 'dotted'),
    ],
  ),
  uiSpec(
    '3-05-ui',
    'Khám phá Video ưu tiên mobile, tạo nội dung, chi tiết thương mại, kiểm duyệt và khiếu nại; tương đương native vẫn bị chặn bởi cổng xác thực.',
    [
      column('Ranh giới bề mặt', [
        node(
          '3-05-auth-entry',
          'Storefront — Creator đã xác thực',
          'Điểm vào trình soạn, gắn thẻ và khiếu nại.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-05-public-entry',
          'Storefront — Buyer/Viewer công khai',
          'Điểm vào feed Video và chi tiết thương mại.',
          'system',
          'Mở rộng',
        ),
        node(
          '3-05-vendor',
          'Vendor Portal',
          'Catalog người bán cấp sản phẩm cho Creator chọn.',
          'seller',
          'Mở rộng',
        ),
        node(
          '3-05-admin',
          'Medusa Admin',
          'Hồ sơ kiểm duyệt, enforcement và khiếu nại theo quyền.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column(
        'Khám phá & tạo',
        [
          node(
            'mh-022',
            'MH-022 Feed Video công khai',
            'Feed Buyer/Viewer công khai ưu tiên mobile, có disclosure, gợi ý sản phẩm và trạng thái ổn định.',
            'system',
            'Mới',
          ),
          node(
            'mh-023',
            'MH-023 Trình soạn',
            'Tải lên, caption, xác thực, bản nháp, thẻ sản phẩm và xuất bản.',
            'creator',
            'Mới',
          ),
          node(
            'mh-024',
            'MH-024 Bộ chọn sản phẩm',
            'Tìm kiếm, chọn và gỡ sản phẩm đủ điều kiện, kèm ngữ cảnh tỷ lệ.',
            'creator',
            'Mới',
          ),
        ],
        true,
      ),
      column('Thương mại & enforcement', [
        node(
          'mh-025',
          'MH-025 Bảng chi tiết Buyer',
          'Chi tiết Video cho Buyer/Viewer, sản phẩm gắn thẻ, voucher và hành động thương mại.',
          'system',
          'Mới',
        ),
        node(
          'mh-026',
          'MH-026 Khiếu nại',
          'Lý do enforcement, tải bằng chứng, trạng thái khiếu nại và tham chiếu.',
          'ops',
          'Mới',
        ),
      ]),
      column('Khép tương đương native', [
        node(
          '3-05-native',
          'Cổng native',
          'Web đáp ứng không khép tương đương native; cần ADR được duyệt, triển khai đã phát hành và bằng chứng native đã xác thực.',
          'system',
          'Cổng xác thực thực địa',
        ),
      ]),
      authoritativeOutcome(
        '3-05',
        'Trang feed, tải lên, điều kiện thẻ, xuất bản, thương mại và kết quả khiếu nại từ BFF/API.',
        'Đang tải có skeleton/tiến độ; lỗi giữ bản nháp; từ chối giải thích trạng thái kiểm duyệt.',
        'Thử lại tải lên hoặc xuất bản an toàn, gỡ thẻ không hợp lệ hoặc thoát qua khiếu nại enforcement.',
        'Phiên bản nội dung, kết quả xuất bản, click sản phẩm, hồ sơ kiểm duyệt và tham chiếu khiếu nại.',
      ),
    ],
    [
      edge('3-05-public-entry', 'mh-022', 'Buyer/Viewer công khai'),
      edge('mh-022', 'mh-025', 'mở bảng chi tiết/sản phẩm'),
      edge('3-05-auth-entry', 'mh-023', 'tạo nội dung đã xác thực'),
      edge('mh-023', 'mh-024', 'chọn sản phẩm'),
      edge('3-05-vendor', 'mh-024', 'catalog người bán hợp lệ'),
      edge('3-05-admin', 'mh-026', 'kiểm duyệt / khiếu nại'),
      edge('mh-024', '3-05-api', 'xuất bản'),
      edge('3-05-remediation', 'mh-026', 'enforcement → khiếu nại'),
      edge('mh-026', '3-05-api', 'nộp khiếu nại'),
      edge('3-05-api', '3-05-native', 'bằng chứng triển khai', 'dashed'),
      edge('3-05-native', '3-05-audit', 'ADR + native xác thực', 'dotted'),
      edge('3-05-api', '3-05-audit', 'nội dung / hồ sơ', 'dotted'),
    ],
  ),
  uiSpec(
    '3-06-ui',
    'Khám phá LIVE ưu tiên mobile, thiết lập và console Host, phòng Viewer, phát lại, kết nối lại và enforcement.',
    [
      column(
        'Ranh giới bề mặt',
        [
          node(
            '3-06-auth-entry',
            'Storefront — Host đã xác thực',
            'Điểm vào thiết lập LIVE và console Host.',
            'creator',
            'Mở rộng',
          ),
          node(
            '3-06-public-entry',
            'Storefront — Viewer công khai',
            'Điểm vào khám phá LIVE và phòng xem trực tiếp.',
            'system',
            'Mở rộng',
          ),
          node(
            '3-06-vendor',
            'Vendor Portal',
            'Catalog người bán cấp sản phẩm cho khay Host.',
            'seller',
            'Mở rộng',
          ),
          node(
            '3-06-admin',
            'Medusa Admin',
            'Kiểm duyệt LIVE và bằng chứng phát lại theo quyền.',
            'ops',
            'Mở rộng',
          ),
        ],
        true,
      ),
      column(
        'Khám phá & Host',
        [
          node(
            'mh-027',
            'MH-027 Khám phá công khai',
            'Thẻ LIVE công khai cho Viewer, lịch, Host, disclosure, gợi ý sản phẩm và trạng thái.',
            'system',
            'Mới',
          ),
          node(
            'mh-028',
            'MH-028 Thiết lập',
            'Lịch Host, metadata, khay sản phẩm và kiểm tra trước khi phát.',
            'creator',
            'Mới',
          ),
          node(
            'mh-029',
            'MH-029 Bảng điều khiển Host',
            'Sức khỏe ingest, ghim sản phẩm, điều khiển chat và trạng thái phiên.',
            'creator',
            'Mới',
          ),
        ],
        true,
      ),
      column('Xem & phát lại', [
        node(
          'mh-030',
          'MH-030 Phòng Viewer công khai',
          'Stream Viewer công khai, khay sản phẩm, mục được ghim, chat, kết nối lại và checkout.',
          'system',
          'Mới',
        ),
        node(
          'mh-031',
          'MH-031 Phát lại',
          'Trạng thái đã kết thúc/phát lại, bằng chứng sản phẩm, enforcement và tham chiếu.',
          'ops',
          'Mới',
        ),
      ]),
      column('Khép tương đương native', [
        node(
          '3-06-native',
          'Cổng native',
          'Web đáp ứng không khép tương đương native; cần ADR được duyệt, triển khai đã phát hành và bằng chứng native đã xác thực.',
          'system',
          'Cổng xác thực thực địa',
        ),
      ]),
      authoritativeOutcome(
        '3-06',
        'Lịch, preflight, phiên, ghim sản phẩm, thương mại Viewer và kết quả phát lại từ BFF/API.',
        'Đang tải tham gia an toàn; lỗi cho phép kết nối lại; từ chối hoặc đã kết thúc sẽ đổi hành động khả dụng.',
        'Kết nối lại phiên đang hoạt động, mở bản phát lại đã kết thúc hoặc thoát an toàn qua hỗ trợ enforcement.',
        'ID phiên, chuyển trạng thái, ghim sản phẩm, hành động Viewer và tham chiếu kiểm duyệt.',
      ),
    ],
    [
      edge('3-06-public-entry', 'mh-027', 'khám phá công khai'),
      edge('3-06-public-entry', 'mh-030', 'deep-link Viewer công khai'),
      edge('mh-027', 'mh-030', 'tham gia phòng Viewer'),
      edge('3-06-auth-entry', 'mh-028', 'Host đã xác thực'),
      edge('3-06-vendor', 'mh-028', 'catalog / khay sản phẩm'),
      edge('3-06-admin', 'mh-031', 'kiểm duyệt / phát lại'),
      edge('mh-028', 'mh-029', 'preflight đạt yêu cầu'),
      edge('mh-029', '3-06-api', 'lệnh Host'),
      edge('mh-030', 'mh-031', 'phát lại/enforcement'),
      edge('mh-030', '3-06-api', 'thương mại Viewer'),
      edge('mh-031', '3-06-api', 'bằng chứng phát lại'),
      edge('3-06-api', '3-06-native', 'bằng chứng triển khai', 'dashed'),
      edge('3-06-native', '3-06-audit', 'ADR + native xác thực', 'dotted'),
      edge('3-06-api', '3-06-audit', 'bằng chứng phiên', 'dotted'),
    ],
  ),
  uiSpec(
    '3-07-ui',
    'Đăng ký Seller PPS và quản lý tỷ lệ, khám phá Creator, chat nội bộ và liên hệ theo phạm vi đồng ý.',
    [
      surfaceBoundary('3-07', [
        node(
          '3-07-vendor',
          'Vendor Portal',
          'Các tuyến Seller PPS, tỷ lệ, danh bạ và chat nội bộ.',
          'seller',
          'Mở rộng',
        ),
        node(
          '3-07-storefront',
          'Storefront',
          'Cài đặt đồng ý liên hệ và tuyến thu hồi của Creator.',
          'creator',
          'Mở rộng',
        ),
      ]),
      column('Hành trình người bán', [
        node(
          'mh-032',
          'MH-032 Đăng ký PPS',
          'Điều kiện, phiên bản điều khoản, trạng thái đăng ký và hành động tiếp theo.',
          'seller',
          'Mới',
        ),
        node(
          'mh-033',
          'MH-033 Tỷ lệ',
          'Nhắm mục tiêu sản phẩm, giá trị hoa hồng, thời điểm hiệu lực và phiên bản.',
          'seller',
          'Mới',
        ),
        node(
          'mh-034',
          'MH-034 Danh bạ',
          'Khám phá Creator, hồ sơ an toàn theo đồng ý và hành động chat nội bộ.',
          'seller',
          'Mới',
        ),
      ]),
      column('Đồng ý của Creator', [
        node(
          'mh-035',
          'MH-035 Đồng ý liên hệ',
          'Phạm vi liên hệ, mục đích, thời hạn, thu hồi và trạng thái hiệu lực.',
          'creator',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-07',
        'Đăng ký PPS, tỷ lệ có hiệu lực, khả năng hiển thị danh bạ và đồng ý liên hệ từ BFF/API.',
        'Đang tải giữ bộ lọc; lỗi cho phép thử lại; từ chối hoặc thu hồi sẽ gỡ dữ liệu liên hệ được bảo vệ.',
        'Thu hồi đồng ý sẽ ẩn thông tin liên hệ nhưng giữ nguyên chat; thoát an toàn về danh bạ phù hợp đồng ý.',
        'Phiên bản điều khoản/tỷ lệ, cấp hoặc thu hồi đồng ý, mục đích disclosure và tham chiếu chat.',
      ),
    ],
    [
      edge('3-07-entry', 'mh-032', 'người bán đã xác thực'),
      edge('3-07-vendor', 'mh-032', 'tuyến Seller PPS'),
      edge('mh-032', 'mh-033', 'đã đăng ký → cấu hình'),
      edge('mh-033', 'mh-034', 'khám phá Creator'),
      edge('mh-034', '3-07-api', 'chat nội bộ'),
      edge('3-07-storefront', 'mh-035', 'đồng ý của Creator'),
      edge('mh-035', '3-07-api', 'cấp / thu hồi'),
      edge('3-07-api', '3-07-audit', 'bằng chứng tỷ lệ và đồng ý', 'dotted'),
    ],
  ),
  uiSpec(
    '3-08-ui',
    'Inbox cộng tác xuyên suốt đề xuất bất biến, hàng mẫu, xét duyệt deliverable, giải ngân và nhánh Seller Affiliate.',
    [
      surfaceBoundary('3-08', [
        node(
          '3-08-storefront',
          'Storefront',
          'Các tuyến inbox cộng tác, hợp đồng, hàng mẫu và deliverable của Creator.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-08-vendor',
          'Vendor Portal',
          'Xét duyệt người bán, giải ngân đã cấp vốn, tranh chấp và dashboard affiliate.',
          'seller',
          'Mở rộng',
        ),
      ]),
      column('Thỏa thuận & thực hiện', [
        node(
          'mh-036',
          'MH-036 Hộp thư Inbox',
          'Hội thoại, trạng thái đề xuất, trạng thái chưa đọc và hành động tiếp theo.',
          'creator',
          'Mới',
        ),
        node(
          'mh-037',
          'MH-037 Đề xuất',
          'Phiên bản hợp đồng bất biến, phí, phạm vi, hạn chót và chấp nhận.',
          'seller',
          'Mới',
        ),
        node(
          'mh-038',
          'MH-038 Sample / Hàng mẫu',
          'Phạm vi địa chỉ, giao hàng, tracking, nhận hàng và trạng thái ngoại lệ.',
          'creator',
          'Mới',
        ),
      ]),
      column('Xét duyệt & phân nhánh', [
        node(
          'mh-039',
          'MH-039 Sản phẩm bàn giao Deliverable',
          'Phiên bản bàn giao, xét duyệt, sửa đổi, phê duyệt và giải ngân.',
          'seller',
          'Mới',
        ),
        node(
          'mh-040',
          'MH-040 Chương trình Seller Affiliate',
          'Trạng thái Seller Affiliate, ưu đãi, hiệu suất và quyết toán.',
          'seller',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-08',
        'Đề xuất, phí đã cấp vốn, giao hàng, deliverable, xét duyệt và kết quả giải ngân từ BFF/API.',
        'Đang tải giữ phiên bản; lỗi cho phép thử lại; từ chối tuân thủ quyền của các bên và quyền cấp vốn.',
        'Sửa đổi/tranh chấp quay về phiên bản hợp đồng bất biến; hủy cung cấp đường thoát an toàn.',
        'Phiên bản hợp đồng và deliverable, giao hàng, cấp vốn, xét duyệt, tranh chấp và tham chiếu giải ngân.',
      ),
    ],
    [
      edge('3-08-entry', 'mh-036', 'điểm vào/xác thực'),
      edge('3-08-storefront', 'mh-036', 'tuyến cộng tác Creator'),
      edge('mh-036', 'mh-037', 'mở đề xuất'),
      edge('mh-037', 'mh-038', 'đã chấp nhận / hàng mẫu'),
      edge('mh-038', 'mh-039', 'đã nhận → bàn giao'),
      edge('mh-039', '3-08-api', 'giải ngân'),
      edge('3-08-vendor', 'mh-040', 'nhánh Seller Affiliate'),
      edge('mh-040', '3-08-api', 'truy vấn dashboard'),
      edge('3-08-remediation', 'mh-037', 'sửa đổi/tranh chấp'),
      edge('3-08-api', '3-08-audit', 'bằng chứng hợp đồng', 'dotted'),
    ],
  ),
  uiSpec(
    '3-09-ui',
    'Đơn MCN, thành viên roster có hiệu lực, RBAC, phân công chiến dịch, báo cáo, phân chia và quyết toán.',
    [
      surfaceBoundary('3-09', [
        node(
          '3-09-storefront',
          'Storefront',
          'Ranh giới MCN chuẩn là apps/storefront/src/app/mcn/*; mọi di chuyển đều cần ADR được phê duyệt.',
          'mcn',
          'Mở rộng',
        ),
        node(
          '3-09-admin',
          'Medusa Admin',
          'Xác minh MCN và giám sát thành viên đã phân quyền.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Thiết lập agency', [
        node(
          'mh-041',
          'MH-041 Đơn đăng ký',
          'Định danh MCN, đại diện, bằng chứng, trạng thái và chỉnh sửa.',
          'mcn',
          'Mới',
        ),
        node(
          'mh-042',
          'MH-042 Danh sách Roster',
          'Lời mời, chấp nhận, thành viên có hiệu lực, rời và thu hồi.',
          'mcn',
          'Mới',
        ),
        node(
          'mh-043',
          'MH-043 Phân quyền RBAC',
          'Vai trò tài khoản phụ, quyền theo phạm vi, thời điểm hiệu lực và thu hồi.',
          'mcn',
          'Mới',
        ),
      ]),
      column('Vận hành & quyết toán', [
        node(
          'mh-044',
          'MH-044 Phân công',
          'Roster đủ điều kiện, phạm vi chiến dịch, vai trò, ngày và trạng thái.',
          'mcn',
          'Mới',
        ),
        node(
          'mh-045',
          'MH-045 Báo cáo',
          'Hiệu suất, phân chia doanh thu, quyết toán, xuất dữ liệu và thông báo.',
          'money',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-09',
        'Đơn đăng ký, thành viên, quyền, phân công, phân chia và quyết toán từ BFF/API.',
        'Đang tải giữ phạm vi; lỗi cho phép thử lại; từ chối phản ánh vai trò và thành viên có hiệu lực.',
        'Rời/thu hồi cập nhật thành viên có hiệu lực và quyền, rồi thoát về tuyến được phép.',
        'Phiên bản thành viên, thay đổi quyền, phân công, quy tắc phân chia, quyết toán và tham chiếu tác nhân.',
      ),
    ],
    [
      edge('3-09-entry', 'mh-041', 'điểm vào/xác thực'),
      edge('3-09-storefront', 'mh-041', 'tuyến MCN Storefront'),
      edge('3-09-admin', 'mh-041', 'giám sát xác minh'),
      edge('mh-041', 'mh-042', 'đã duyệt → roster'),
      edge('mh-042', 'mh-043', 'thành viên → RBAC'),
      edge('mh-043', 'mh-044', 'phân công đã phân quyền'),
      edge('mh-044', 'mh-045', 'báo cáo / quyết toán'),
      edge('mh-042', '3-09-api', 'rời / thu hồi'),
      edge('mh-045', '3-09-api', 'truy vấn / xuất dữ liệu'),
      edge('3-09-api', '3-09-audit', 'thành viên / phân chia', 'dotted'),
    ],
  ),
  uiSpec(
    '3-10-ui',
    'Ví Creator, thiết lập thuế và thanh toán, sao kê và khắc phục, cùng đối soát tài chính.',
    [
      surfaceBoundary('3-10', [
        node(
          '3-10-storefront',
          'Storefront',
          'Các tuyến ví, thiết lập, sao kê và thông báo của Creator.',
          'money',
          'Mở rộng',
        ),
        node(
          '3-10-admin',
          'Medusa Admin',
          'Vai trò tài chính mở bàn làm việc đối soát đã phân quyền.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Tài chính Creator', [
        node(
          'mh-046',
          'MH-046 Ví',
          'estimated, approved, payable, paid và held là trạng thái số dư; reversed là bút toán bù trừ, không phải trạng thái số dư.',
          'money',
          'Mới',
        ),
        node(
          'mh-047',
          'MH-047 Thuế/thanh toán',
          'Định danh, thuế, phương thức thanh toán, xác minh và che dữ liệu an toàn.',
          'money',
          'Mới',
        ),
        node(
          'mh-048',
          'MH-048 Sao kê',
          'Kỳ, bút toán order-line, điều chỉnh, payout và xuất dữ liệu.',
          'money',
          'Mới',
        ),
      ]),
      column('Ngoại lệ & tài chính', [
        node(
          'mh-049',
          'MH-049 Khắc phục',
          'Deep-link thông báo cho nguyên nhân held/thất bại và hành động an toàn.',
          'creator',
          'Mới',
        ),
        node(
          'mh-050',
          'MH-050 Đối soát',
          'Ngoại lệ theo vai trò tài chính, kết quả provider, thử lại và chỉnh sửa.',
          'ops',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-10',
        'Trạng thái ví, xác minh, sao kê, payout và kết quả đối soát từ BFF/API.',
        'Đang tải không bao giờ hiển thị số không như dữ kiện; lỗi cho phép thử lại; từ chối bảo vệ dữ liệu thuế và thanh toán.',
        'held/thất bại dẫn đến hành động an toàn, thử lại provider, chỉnh sửa, hỗ trợ hoặc thoát an toàn.',
        'Bút toán ledger, xác minh, lần thử payout, phản hồi provider, chỉnh sửa và tham chiếu hồ sơ.',
      ),
    ],
    [
      edge('3-10-entry', 'mh-046', 'điểm vào/xác thực'),
      edge('3-10-storefront', 'mh-046', 'tuyến ví Creator'),
      edge('mh-046', 'mh-047', 'cần thiết lập'),
      edge('mh-047', 'mh-048', 'đã xác minh → sao kê'),
      edge('3-10-entry', 'mh-049', 'deep-link thông báo'),
      edge('3-10-admin', 'mh-050', 'vai trò tài chính'),
      edge('mh-049', '3-10-api', 'hành động an toàn'),
      edge('mh-050', '3-10-api', 'đối soát / chỉnh sửa'),
      edge('3-10-api', '3-10-audit', 'bằng chứng tài chính', 'dotted'),
    ],
  ),
  uiSpec(
    '3-11-ui',
    'Báo cáo gian lận và khiếu nại của người dùng, cùng hàng đợi quản trị, đồ thị bằng chứng, enforcement và thu hồi chính sách.',
    [
      surfaceBoundary('3-11', [
        node(
          '3-11-storefront',
          'Storefront',
          'Các tuyến báo cáo người dùng, thông báo enforcement và khiếu nại.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-11-admin',
          'Medusa Admin',
          'Hàng đợi rủi ro, đồ thị hồ sơ, hành động phá hủy và điều khiển thu hồi.',
          'ops',
          'Mở rộng',
        ),
      ]),
      column('Báo cáo & điều tra', [
        node(
          'mh-051',
          'MH-051 Báo cáo gian lận',
          'Danh mục, tham chiếu thực thể, bằng chứng, disclosure và biên nhận.',
          'creator',
          'Mới',
        ),
        node(
          'mh-052',
          'MH-052 Hàng đợi rủi ro',
          'Ưu tiên, trạng thái, người phụ trách, phiên bản chính sách và bộ lọc an toàn.',
          'ops',
          'Mới',
        ),
        node(
          'mh-053',
          'MH-053 Đồ thị hồ sơ',
          'Đồ thị bằng chứng đã phân quyền, quyết định, enforcement và lý do.',
          'ops',
          'Cổng xác thực thực địa',
        ),
      ]),
      column('Khiếu nại & thu hồi', [
        node(
          'mh-054',
          'MH-054 Khiếu nại',
          'Tham chiếu enforcement, bằng chứng khiếu nại, trạng thái và kết quả.',
          'creator',
          'Mới',
        ),
        node(
          'mh-055',
          'MH-055 Thu hồi',
          'Phạm vi người vận hành chính sách, tài sản bị ảnh hưởng, xác nhận và rollback.',
          'ops',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-11',
        'Kết quả báo cáo, hồ sơ, chính sách, enforcement, khiếu nại và thu hồi từ BFF/API.',
        'Đang tải giữ định danh hồ sơ; lỗi cho phép thử lại; từ chối ẩn bằng chứng và hành động bị hạn chế.',
        'Mọi hành động phá hủy đều phải xác nhận và trả về tham chiếu; khiếu nại/hỗ trợ cung cấp lối thoát an toàn.',
        'Biên nhận người báo cáo, phiên bản bằng chứng, quyết định, tác nhân, khiếu nại, thu hồi và tham chiếu tương quan.',
      ),
    ],
    [
      edge('3-11-entry', 'mh-051', 'điểm vào/xác thực'),
      edge('3-11-storefront', 'mh-051', 'tuyến báo cáo người dùng'),
      edge('mh-051', 'mh-052', 'hàng đợi quản trị'),
      edge('mh-052', 'mh-053', 'mở đồ thị hồ sơ'),
      edge('mh-053', 'mh-054', 'enforcement → khiếu nại'),
      edge('3-11-admin', 'mh-055', 'người vận hành chính sách'),
      edge('mh-053', '3-11-api', 'xác nhận enforcement'),
      edge('mh-054', '3-11-api', 'nộp khiếu nại'),
      edge('mh-055', '3-11-api', 'xác nhận thu hồi'),
      edge('3-11-api', '3-11-audit', 'bằng chứng được bảo toàn', 'dotted'),
    ],
  ),
  uiSpec(
    '3-12-ui',
    'Đăng ký thuộc tính ngoài nền tảng, YouTube OAuth, sức khỏe và khắc phục product feed, cùng báo cáo kênh.',
    [
      surfaceBoundary('3-12', [
        node(
          '3-12-storefront',
          'Storefront',
          'Các tuyến thuộc tính, kết nối, feed, thẻ và báo cáo của Creator.',
          'creator',
          'Mở rộng',
        ),
        node(
          '3-12-oauth',
          'OAuth bên ngoài',
          'Ranh giới phân quyền YouTube, đồng ý phạm vi, callback và thu hồi.',
          'system',
          'Mới',
        ),
      ]),
      column('Kết nối kênh', [
        node(
          'mh-056',
          'MH-056 Thuộc tính',
          'Đăng ký thuộc tính, xác minh quyền sở hữu, disclosure và trạng thái.',
          'creator',
          'Mới',
        ),
        node(
          'mh-057',
          'MH-057 Kết nối YouTube OAuth',
          'Phạm vi được yêu cầu, đồng ý của provider, callback và ngắt kết nối.',
          'system',
          'Mới',
        ),
      ]),
      column('Vận hành & báo cáo', [
        node(
          'mh-058',
          'MH-058 Sức khỏe feed',
          'Đồng bộ catalog, lỗi mục/thẻ, lần thành công gần nhất và khắc phục.',
          'creator',
          'Mới',
        ),
        node(
          'mh-059',
          'MH-059 Báo cáo kênh',
          'Click bên ngoài, đơn được attribution, thu nhập và độ mới dữ liệu.',
          'money',
          'Mới',
        ),
      ]),
      authoritativeOutcome(
        '3-12',
        'Xác minh thuộc tính, trạng thái OAuth, đồng bộ feed, thẻ và báo cáo kênh từ BFF/API.',
        'Đang tải giữ trạng thái provider; lỗi hỗ trợ thử lại; từ chối xử lý an toàn phạm vi bị mất.',
        'Ngắt kết nối/kết nối lại giữ nguyên lịch sử và trạng thái an toàn; thẻ thất bại liên kết đến khắc phục.',
        'Bằng chứng thuộc tính, cấp/thu hồi OAuth, lần chạy feed, lỗi thẻ, click, đơn hàng và tham chiếu báo cáo.',
      ),
    ],
    [
      edge('3-12-entry', 'mh-056', 'điểm vào/xác thực'),
      edge('3-12-storefront', 'mh-056', 'tuyến thuộc tính Creator'),
      edge('mh-056', 'mh-057', 'kết nối YouTube'),
      edge('mh-057', 'mh-058', 'có quyền → đồng bộ feed'),
      edge('mh-058', 'mh-059', 'feed khỏe → báo cáo'),
      edge('mh-057', '3-12-oauth', 'phân quyền / thu hồi'),
      edge('mh-058', '3-12-api', 'đồng bộ / khắc phục thẻ'),
      edge('mh-059', '3-12-api', 'truy vấn báo cáo'),
      edge('3-12-api', '3-12-audit', 'bằng chứng kênh', 'dotted'),
    ],
  ),
];
